### ISSUE TITLE
gist workflow

### ISSUE THREAD

**Issue by jueyang** [amandabee/CUNY-data-skills#1]
Hi all,

To follow up the last class, here's a workflow from gist to a web page. Let me know if you need other clarifications on GitHub/gist or markdown, or any aspect of this process.
1. Edit your pitch gist with [Markdown](https://guides.github.com/features/mastering-markdown/)
2. Paste everything you have there in http://dillinger.io/ (or Mou, if you have it, either is fine), and export the file `as html`. In dillinger.io the export it's on the top-right corner:
   
   ![](http://cl.ly/image/4106403q0n3B/Screen%20Shot%202015-02-17%20at%2010.29.38%20PM.png)
3. Open the html export in your text editor. Copy the whole thing.
4. Go to your gist, replace your markdown with the html you just copied.
5. Save the gist with the name `index.html`:
   
   ![](http://cl.ly/image/0M0A260J2x3A/Screen%20Shot%202015-02-17%20at%2010.33.59%20PM.png)
6. To view your gist on blocks: replace `https://gist.github.com` with `bl.ocks.org`
7. Click on `open in a new window`. That's your web page.

@sfdevlin
@BurgosNY
@riogringa
@JuliaJRH
@cristinafurlong
@sihemsf
@jwasserman
@adrieleparker
@emily-goldblum
@ericalucia
@DeronDalton
@lmechegaray
@aaronsimon
@BetsyBagel

**Comment by amandabee** [comment]
Folks, for now, you _don't_ need to worry about saving your gists as HTML. We can work with Mardown. We'll get to HTML later.
