### ISSUE TITLE
NYC data resource + Code Across NYC this weekend (feb 21/22)

### ISSUE THREAD

**Issue by jueyang** [amandabee/CUNY-data-skills#2]
Hey all,

Here're some great [data resources](https://docs.google.com/spreadsheets/d/1R7O_FZLNB8VV5eoPDNATb-f0njjUsJwmz22cT_OB3fw/edit#gid=0) if you are dealing with NYC data. The civic hacker group, http://betanyc.us/, curated it. 

This weekend is the [Code Across NYC](https://www.eventbrite.com/e/codeacross-nyc-2015-nycs-opendata-civictech-festival-tickets-15578652168) hackathon -- there will be open data and data skills workshop and unconferences. If any of you are going, you can find me there.

PS1. Can anyone forward this to @cristinafurlong? Apparently it's not a valid github handle...
PS2. @BetsyBagel said I should give a shout to my website. (Thx!) Here it is. http://goodlemons.com

@sfdevlin
@BurgosNY
@riogringa
@JuliaJRH
@sihemsf
@jwasserman
@adrieleparker
@emily-goldblum
@ericalucia
@DeronDalton
@lmechegaray
@aaronsimon
@BetsyBagel

**Comment by amandabee** [comment]
Pretty sure it's @cristinafurlong
