### ISSUE TITLE
Making maps: a few general concepts

### ISSUE THREAD

**Issue by jueyang** [amandabee/CUNY-data-skills#3]
@ericalucia stopped by my desk today and brought up a few good points about making maps. Ah,  maps. You probably realized there're a lot of layers of information packed into this one single concept. This thread might fill in some knowledge gaps when you are dealing with geographic data.
### READ THIS

http://mapschool.io/

What the heck goes into a map? Read at least the bolded titles from the linked page above, a crash course in maps. Know the difference between an image and a shape, and pay attention to how data is associated with geometries.
### Shapefiles
1. **What is a shapefile?** When you download a shapefile and unzip the folder, you will find a bunch of things besides the `.shp`. For now, just know that the `.shp` is dependent on the other stuff (`.shx`, `.dbf`, etc etc,) and you will probably never interact with these other stuff directly individually. [Read more](http://en.wikipedia.org/wiki/Shapefile#Overview)
2.  **How to use a shapefile in CartoDB?** Upload your zipped shapefile (as opposed to the unzipped one) to CartoDB, as a table.
### Geo reference

You have data. You need to associate data to geometries. And then you symbolize the geometries in some way according to a data value. You might have heard of the term, visualization? Yeah, that's the last part -- the symbolization. For example, put a dot on it. 

Getting your data in shape (no pun intended) takes 90% of the time when you try to make a map, and the rest is just to make it appear.

Here's [a tutorial](http://docs.cartodb.com/tutorials/how_to_georeference.html) from CartoDB in terms of georeferencing your dataset.
### Data join

Some of you might be dealing with dataset that share a common column with a shapefile, such as zipcode. I'll pass on a metaphor from my GIS professor back in the days: think of that common column as a hook. You need to hook two datasets together -- one with geometries, one without.

In that case you would want to join the column of two tables, please consult [this tutorial](http://docs.cartodb.com/tutorials/joining_data.html).
### More mapping concepts?

If you are confused by any of these concepts and/or how to do them in CartoDB, please let me know. To be honest I haven't used CartoDB's interface that much, so I might not know where the button is immediately, but I'll sit with you and figure out how you would go about a problem and unpack some dense processes for you. Hope it helps!

Carry on y'all :athletic_shoe: :athletic_shoe: 

@sfdevlin
@BurgosNY
@riogringa
@JuliaJRH
@cristinafurlong
@sihemsf
@jwasserman
@adrieleparker
@emily-goldblum
@DeronDalton
@lmechegaray
@aaronsimon
@BetsyBagel

**Comment by amandabee** [comment]
See also:
- https://github.com/amandabee/CUNY-SOJ-data-storytelling/wiki/Tip-Sheet:-Geocoding  
- https://github.com/amandabee/CUNY-SOJ-data-storytelling/wiki/Where-to-Find-Shapefiles
- http://amandabee.github.io/CUNY-data-skills/hands-on/mapping.html
