### ISSUE TITLE
installing csvkit error

### ISSUE THREAD

**Issue by JuliaJRH** [amandabee/CUNY-data-skills#5]
Do I need to install something else before I try to install csvkit? I don't have Python installed, and I'm getting this error when I follow the instructions (from http://csvkit.readthedocs.org/en/latest/install.html) to install csvkit:

Julias-MacBook-Pro:~ juliahaslanger$ pip install csvkit
-bash: pip: command not found

And if I do need to install python, do you want me to install Python 2 or 3? (Both options are listed on [the python install page https://www.python.org/downloads/mac-osx/)

**Comment by amandabee** [comment]
An OSX Mac should have python installed, but may not have `pip` installed.  You can find out by running `which python` (or `python --version` -- which will tell you the version you have or give you a "not found" error if python isn't there at all). And then you should be able to use `easy_install` to install `pip` -- we'll go through this in class, though!

**Comment by amandabee** [comment]
Feel free to re-open if you're still stuck.
