### ISSUE TITLE
Prep for summer product dev class

### ISSUE THREAD

**Issue by jueyang** [amandabee/CUNY-data-skills#6]
Hey folks,

I'll be in the class today to get a sense of what you have/need for the summer class on product development. If you have a sec before class to answer some questions regarding your idea and current state with the community you are working with, it'd be great! Otherwise we'll chat in class.

Questions are here: https://jue.typeform.com/to/DGUP52

@sfdevlin
@BurgosNY
@riogringa
@JuliaJRH
@sihemsf
@jwasserman
@adrieleparker
@emily-goldblum
@ericalucia
@DeronDalton
@lmechegaray
@aaronsimon
@BetsyBagel
@cristinafurlong

**Comment by amandabee** [comment]
I think we've got this.
