### ISSUE TITLE
Add Data Visualization tools list to CUNY-data-skills/hands-on/visual_encoding.html

### ISSUE THREAD

**Issue by edoardo-bluframe** [amandabee/CUNY-data-skills#7]
Add Data Visualization Tools list: http://inspire.blufra.me/big-data-visualization-review-of-the-20-best-tools/

To this page: https://amandabee.github.io/CUNY-data-skills/hands-on/visual_encoding.html

**Comment by amandabee** [comment]
Not sure how I managed to avoid seeing this, but I just see it now and ... `inspire.blurfa.me` doesn't seem to be loading. I'm happy to take a look at a resource I may have missed in that list, but I'm not able to load this.
